[package]
name = "zerotier-central-api"
version = "1.3.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
progenitor = "0.8.0"
reqwest = { version = "0.12.8", features = ["json", "stream"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
