[package]
name = "zeronsd"
version = "0.1.0"
authors = ["Erik Hollensbe <linux@hollensbe.org>", "Adam Ierymenko <adam.ierymenko@zerotier.com>"]
homepage = "https://github.com/zerotier/zeronsd"
repository = "https://github.com/zerotier/zeronsd"
documentation = "https://github.com/zerotier/zeronsd/blob/main/README.md"
license-file = "LICENSE"
readme = "README.md"
keywords = ["dns", "zerotier"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = ">= 0"
anyhow = ">= 0"
clap = ">= 0"
cidr-utils = ">= 0"
trust-dns-resolver = "*"
trust-dns-server = { version = "0.20.1", features = ["trust-dns-resolver"] } 
tokio = { version = "1", features = ["full"] }
zerotier-central-api = { path = "./zerotier-central-api", version = "*" }
zerotier-one-api = { path = "./zerotier-one-api", version = "*" }
