[package]
name = "zeronsd"
version = "0.1.0"
authors = ["Erik Hollensbe <linux@hollensbe.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = ">= 0"
anyhow = ">= 0"
clap = ">= 0"
cidr-utils = ">= 0"
trust-dns-resolver = "*"
trust-dns-server = { version = "0.20.1", features = ["trust-dns-resolver"] } 
tokio = { version = "1", features = ["full"] }
central = { path = "central" }
service = { path = "service" }
